version: '3.8'

services:
  dispatcher:
    build:
      context: .
      dockerfile: docker/dispatcher/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
    command: ["./dispatcher", "--config", "config/dispatcher.yaml"]

  validator:
    build:
      context: .
      dockerfile: docker/validator/Dockerfile
    volumes:
      - ./config:/app/config
    command: ["./validator", "--config", "config/validator.yaml"]
    depends_on:
      - dispatcher 